# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIfirst3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1243, 860)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 1241, 811))
        self.frame_5.setStyleSheet("QFrame {\n"
"    background-color: #3D3D3D; /* Dark Grey */\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_5)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: white; \n"
"    \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(190, 50, 131, 31))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color:white;\n"
"    background-color:black;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(60, 40, 121, 51))
        self.label.setStyleSheet("\n"
"QLabel {\n"
"    font-size: 19px;\n"
"    font-weight: bold;\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(370, 50, 191, 31))
        self.label_2.setStyleSheet("QLabel {\n"
"    font-size: 19px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(570, 50, 61, 31))
        self.label_3.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(770, 50, 71, 31))
        self.label_4.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(60, 100, 211, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* Green */\n"
"    color: white;\n"
"    font-size: 19px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(1010, 50, 111, 31))
        self.radioButton.setStyleSheet("QRadioButton {\n"
"    color: black; /* Set text color */\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.radioButton.setObjectName("radioButton")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(880, 200, 261, 231))
        self.frame_2.setStyleSheet("\n"
"QFrame {\n"
"    background-color: #D3D3D3; /* Gray for placeholders */\n"
"    border-radius: 10px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(4, -5, 251, 241))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(880, 470, 261, 231))
        self.frame_3.setStyleSheet("\n"
"QFrame {\n"
"    background-color: #D3D3D3; /* Gray for placeholders */\n"
"    border-radius: 10px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(4, -5, 251, 251))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(49, 199, 791, 511))
        self.frame_4.setStyleSheet("QFrame {\n"
"    background-color: #D3D3D3; /* Gray for placeholders */\n"
"    border-radius: 10px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 20, 151, 41))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: black;  \n"
"    color: white;\n"
"    font-size: 16px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(-6, 5, 791, 551))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(60, 160, 271, 31))
        self.label_5.setStyleSheet("\n"
"QLabel {\n"
"    font-size: 19px;\n"
"    font-weight: bold;\n"
"    color:red;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(640, 50, 111, 31))
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    background-color: black; /* Dark Grey */\n"
"    color: white; /* Optional: Set text color for contrast */\n"
"    border-radius: 5px; /* Optional: Add rounded corners */\n"
"    padding: 5px; /* Optional: Add some padding */\n"
"}\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_2.setGeometry(QtCore.QRect(840, 50, 111, 31))
        self.textEdit_2.setStyleSheet("QTextEdit {\n"
"    background-color: black; /* Dark Grey */\n"
"    color: white; /* Optional: Set text color for contrast */\n"
"    border-radius: 5px; /* Optional: Add rounded corners */\n"
"    padding: 5px; /* Optional: Add some padding */\n"
"}\n"
"")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.pushButton.raise_()
        self.radioButton.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.label_5.raise_()
        self.comboBox.raise_()
        self.textEdit.raise_()
        self.textEdit_2.raise_()
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1243, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Bathroom"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Bedroom"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Livingroom"))
        self.label.setText(_translate("MainWindow", "Room Type:"))
        self.label_2.setText(_translate("MainWindow", "Room Dimensions:"))
        self.label_3.setText(_translate("MainWindow", "Length"))
        self.label_4.setText(_translate("MainWindow", "Width"))
        self.pushButton.setText(_translate("MainWindow", "Generate"))
        self.radioButton.setText(_translate("MainWindow", "Bathtub"))
        self.pushButton_2.setText(_translate("MainWindow", "Feedback"))
        self.label_5.setText(_translate("MainWindow", "Generated Layouts Preview"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
